### ISSUE TITLE
Dashboard - Controls

### ISSUE THREAD

**Issue by bgarner** [fgldevteam/portal#143]
- [x] Rename button **Cancel** to **Undo changes**
- [x] Change **Undo changes** icon from cancel/close to the undo icon
  - [x] **Undo changes** should be disabled when no changes have been initiated
  - [x] Undo functionality otherwise unchanged (i.e. clicking it restores the last saved Title, Subtitle and background image values)
- [x] button **Save changes** should use a save icon

![admin-dashboard-form-title_plus_branding](https://cloud.githubusercontent.com/assets/69516/13333344/d6971d84-dbc3-11e5-90cf-dd6710bd361a.png)

**Comment by bgarner** [comment]
**QA**
- [ ] Rename button **Cancel** to **Undo changes**
- [ ] Change **Undo changes** icon from cancel/close to the undo icon
  - [ ] **Undo changes** should be disabled when no changes have been initiated
  - [ ] Undo functionality otherwise unchanged (i.e. clicking it restores the last saved Title, Subtitle and background image values)
- [ ] button **Save changes** should use a save icon
- [ ] **Save changes** should be disabled when:
  - [ ] no changes are pending (e.g. page load or immediately following save)
  - [ ] changes are invalid (e.g. either/both required fields are empty)

We are using the same feedback mechanism throughout. If we need to change this, we should do it on a global level. 
> - [ ] Saving changes should not generate a modal.
>   - [ ] display text *Changes saved.* preceded by checkmark icon just above the button
>   - [ ] button reverts to disabled state
>   - [ ] message fades out after 5 seconds, OR
>   - [ ] if any fields within the section change within less than 5 seconds

**Comment by darylsuttie** [comment]
@bgarner checked items pass QA

* agree that error handling needs a global issue assigned/created
* disabled means attribute disabled should be applied to the element, not that it is usable but doesn't do anything (but see above point)
* I somehow broke the background image selector, and interacting with it is strange. I'll create a new issue for this.

- [ ] **Undo** button should read **Undo changes**
- [ ] **Save changes** triggers a dialog/modal 100% of the time instead of only when something's changed
- [ ] Add a space in front of the text for the  **Change...** button

**Comment by darylsuttie** [comment]
Closing this issue.

* Issue #181 created re: error handling
* Issue #176 created to address bg selector interaction inconsistencies
